Purge api added to remove expired keys
prologic/bitcask pull request #204
Opened 2020-12-28 04:27 UTC by yashschandra

for #203

2020-12-28 05:06 UTC, prologic approved these changes

2020-12-28 05:06 UTC, prologic commented on bitcask.go
> +	ttlIndex   art.Tree
Does the TTL Index need to be an Adaptive Radix Tree?

2020-12-28 05:14 UTC, yashschandra commented on bitcask.go
> +	ttlIndex   art.Tree
It can be any data structure that can map key to its TTL. I chose ART because I thought it would be space efficient, we are already using it and it supports []byte as key (map does not).

2020-12-28 05:15 UTC, yashschandra commented
@prologic we will also need to look into how can we mock things well to increase test coverage. Right now its hard to test error cases for file operations.

2020-12-28 05:21 UTC, prologic commented
Agreed maybe use io.Reader / io.writer in places?

2020-12-28 05:21 UTC, prologic commented on bitcask.go
> +	ttlIndex   art.Tree
Ahh this is true

2020-12-28 20:49 UTC, Hassall requested changes

2020-12-28 20:49 UTC, Hassall commented on bitcask.go
> +func (b *Bitcask) purge() (err error) {
Deletion of expired keys depends on users calling purge. I don't see this is a viable solution to expired keys in memory. 

Instead of having the option to 'purge' keys, users should be given an eviction function on how to handle evicted keys (which they may want to do nothing). And in the backend, we evict keys whose time expires and call the eviction function.

2020-12-28 21:59 UTC, prologic commented on bitcask.go
> +func (b *Bitcask) purge() (err error) {
But this will only work as long as you read expires keys?

2020-12-28 23:33 UTC, Hassall commented on bitcask.go
> +func (b *Bitcask) purge() (err error) {
Not sure what you mean.

With my approach, everything here would have to change. As mentioned before, gcache is a library that already provides this functionality.

2020-12-29 04:46 UTC, yashschandra commented on bitcask.go
> +func (b *Bitcask) purge() (err error) {
We may need to sit down and think which approach we want to implement (automatic or on-demand deletion)

2020-12-29 05:33 UTC, prologic commented on bitcask.go
> +func (b *Bitcask) purge() (err error) {
I just don't want the _library_ to be doing this as I _think_ it should be the application's responsibility to cleanup keys. But maybe OTOH cleaning up expired keys isn't that expensive or a big deal to do automatically? I'm not sure...

2020-12-29 17:31 UTC, Hassall commented on bitcask.go
> +func (b *Bitcask) purge() (err error) {
Well the problem as I see it is, leaving the responsibility of 'purge' (deleting expired keys) to the user is never a good option. 

Several things could go wrong such as: 
- they never call it
- they call it too often (we iterate through **all** keys that have some time expiry)

Why not take the burden off them and only ask for their desired behavior of evicted keys. Let us behind the scenes decide on how we deal with expired keys.

2020-12-29 22:34 UTC, prologic commented on bitcask.go
> +func (b *Bitcask) purge() (err error) {
> Why not take the burden off them and only ask for their desired behavior of evicted keys. Let us behind the scenes decide on how we deal with expired keys.

This is a good compromise. One of the options can also be to disable the feature entirely.

2021-01-03 06:12 UTC, yashschandra commented on bitcask.go
> +func (b *Bitcask) purge() (err error) {
Happy new year folks !

@Hassall I have one question regarding `gcache` library, I was not able use `[]byte` for keys like we do in `bitcask` (`gcache` panics), how did you test it for lfu?

2021-01-03 18:37 UTC, Hassall commented on bitcask.go
> +func (b *Bitcask) purge() (err error) {
@yashschandra 

Taking a better look at gcache, it seems like the repo hasn't been updated in a while. There also seems to be a concerning issue about memory leak. Perhaps you could find an alternative library.

2021-01-03 22:36 UTC, prologic commented on bitcask.go
> +func (b *Bitcask) purge() (err error) {
Perhaps the original approach still has merit, with modifications?

2021-01-04 15:27 UTC, yashschandra commented on bitcask.go
> +func (b *Bitcask) purge() (err error) {
@prologic  original approach meaning providing a "purge" api?

2021-01-05 08:59 UTC, prologic commented on bitcask.go
> +func (b *Bitcask) purge() (err error) {
Yes

2021-01-05 09:49 UTC, yashschandra commented on bitcask.go
> +func (b *Bitcask) purge() (err error) {
Cool. Any review comments you have for this PR?

2021-01-05 11:20 UTC, prologic commented on bitcask.go
> +func (b *Bitcask) purge() (err error) {
I don't think you've change any code since my last review right? And IIRC I approved it initially. I respect @Hassall 's opinion here, but gocache doesn't seem viable here and letting the user/application decide IHMO is better than the library automagically handling this.

2021-01-05 11:22 UTC, prologic commented on bitcask.go
> +func (b *Bitcask) Purge() error {
Only final comment is:

> Maybe `GC()` is a better name for the new API method? Since it describes better what it does "garbage collection"? 🤔

2021-01-05 11:22 UTC, prologic submitted a review, later dismissed

2021-01-06 11:42 UTC, prologic approved these changes

2021-01-12 14:04 UTC, yashschandra commented
@Hassall since we decided to go ahead with exposing "GC" as an api, can you review this pr?

2021-03-14 00:50 UTC, prologic commented
What's happening with this PR?

2021-03-14 08:01 UTC, yashschandra commented
@Hassall 's review is pending

2021-06-01 04:03 UTC, taigrr commented
Sorry to bother, but any update on this PR?

2021-06-01 07:57 UTC, prologic commented
@yashschandra I think I've reviewed this before. I _think_ it's fine. If you're good I'll merge it tonight?

2021-06-01 19:05 UTC, yashschandra commented
@prologic we good, can go ahead and merge it

2021-06-01 20:47 UTC, merged